### ISSUE TITLE
Weapon with apostrophe in name doesn't get saved, ie Sakpata's Fists

### ISSUE THREAD

**Issue by momotaroko** [ekrividus/autoSC#1]
When I load the addon, add the ws to the weapon Sakpata's Fists, everything works fine.
It's a problem when I reload the addon after computer reboot that it doesn't work and the xml file doesn't get saved because it shows that it doesn't accept the "'" (apostrophe character) in the name of the weapon.
<sakpata's_fists>Asuran Fists</sakpata's_fists>

How to make it so that the xml settings file get saved when using a weapon that has an apostrophe in its name?

**Comment by ekrividus** [comment]
Special symbols need to be escaped for saving. I'll see about getting this sorted this weekend.

**Comment by momotaroko** [comment]
> Special symbols need to be escaped for saving. I'll see about getting this sorted this weekend.

Thank you for looking into it and for all your work! Your addons are AMAZING.

**Comment by ekrividus** [comment]
Thanks, and the newest one should properly handle "'".
