### ISSUE TITLE
Issue loading on MNK

### ISSUE THREAD

**Issue by ithorien** [ekrividus/autoSC#2]
Hi there, found your addon through random searches as one of the better ones handling skillchains, but am having issues running it on my monk. Here's what I get just loading the addon:

autoSC: Lua runtime error: autosc/autosc.lua:557: attempt to index field '?' (a nil value)

I haven't noticed this yet on other jobs; I have a THF and WHM in party right now that are successfully loading/using the addon, just not monk. Presumably something with weapon slots? But I'm no expert, so I defer to you! Let me know what I can provide to help.

**Comment by ekrividus** [comment]
What weapon were you using? 
I'm just about to login and will see if I can make this happen on my own mnk, but I think the only time it's ever failed is when there was no weapon in the main hand at load. I believe that was resolved though.

**Comment by ithorien** [comment]
The weapon I'm using when this occurs is Jolt Counters ID# 21506, and honestly didn't even think it could be something with the weapon itself. I just swapped to any other H2H and it seems to be fine, so it must be something related to that weapon.

**Comment by ithorien** [comment]
Figured it out; it has nothing to do with the weapon/job/etc., and everything to do with the fact I'm _that_ guy, and have more than 4 wardrobes. Jolt counters were in 5, and the second I moved them to any regular inventory or wardrobe =< 4 it worked, which I then confirmed with your lua as you have up to 4 listed. 

If you can add support for my types, it would be much appreciated I'm sure. I've modified my local to add support for those extra inventories so personally I'm all set.

**Comment by ekrividus** [comment]
Yes I will absolutely add those. I don't know how, since I also have more than 4, I didn't do that for this soon after they added the new ones. 
Should be updated tonight.

**Comment by ithorien** [comment]
Haha well, and I'm assuming, but if you're anything like me in this regard as well, then you have way too much going on and changing things in 590323 files is sometimes quite daunting and things just slip. Thanks for the awesome addon!

**Comment by ekrividus** [comment]
And the new wardrobes are added, just a couple months late :)
Yeah I end up working on maybe one too many things at a time, life, etc. and sometimes just forget I have a thing going lol
