### ISSUE TITLE
Stops running after a few hours

### ISSUE THREAD

**Issue by Jerukhalri** [ekrividus/autoSC#3]
First, this is an incredible addon! I don't know how I played for so long without it, but there's an issue that causes it to stop functioning after about 3 hours of continuous play. When I bring up the console I see the following line:

AutoSC: Lua runtime error: autosc/autosc.lua:246: attempt to index global 'player' (a nil value)

When I try to bring up the UI, I see the first line (--- Auto Skillchains) but nothing shows beneath it. If I reload the addon, it starts working, but it eventually stops functioning again, usually within half an hour.

Settings:
Weapon: Ochu
Open new SC? No
      Using: None
Wait for SC effect? No
Use ranged: No
     Prefer ranged? No
Close SC Level:
1: No  2: No  3: Yes  4: Yes
Target SC Level: 3
WS Window:
      Begin: 2.75  End: 8
Filtered WSs:
   None

**Comment by ekrividus** [comment]
I'm glad you like it. It's always nice to hear that it is making lives easier.
This is the strangest error, considering when it happens, anywho. I added a check that will hopefully eliminate that.

**Comment by Jerukhalri** [comment]
Sweet! Trying it now!

**Comment by Jerukhalri** [comment]
12 hours later and it's still going! YOU ROCK!!!  \\(^.^)/

**Comment by ekrividus** [comment]
Glad that got sorted out :)
